// Generated by CoffeeScript 1.4.0
(function() {
  var bot, channels, irc, wolfram;

  require('coffee-script');

  irc = require('irc');

  wolfram = require('./wolfram');

  channels = ['##the_basement'];

  bot = new irc.Client('irc.freenode.net', 'Marflow', {
    channels: channels
  });

  bot.addListener('message', function(from, to, text, message) {
    var query, regexs;
    regexs = {
      addInsult: /^[!]\s*add\s+insult\s+(\w*)\s+(\S*)$/,
      insult: /^[!]\s*insult\s+(\S+)$/,
      question: /^[?](.*)$/
    };
    if (regexs.question.test(text)) {
      query = text.replace(/^[?]\s*/g, '');
      return wolfram.request(query, function(answer) {
        return bot.say(channels[0], answer);
      });
    }
  });

}).call(this);
